//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publicacion()
        {
            this.encontrado = new HashSet<encontrado>();
            this.mensajeria = new HashSet<mensajeria>();
            this.publicacionFoto = new HashSet<publicacionFoto>();
            this.venta = new HashSet<venta>();
        }
    
        public int ID_Publicacion { get; set; }
        public int Tipo_Publicacion { get; set; }
        public byte ID_Categoria { get; set; }
        public byte ID_SubCategoria { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte Estado_Publicacion { get; set; }
        public int ID_Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Estado_Producto { get; set; }
        public double Precio { get; set; }
        public Nullable<int> Estado_Visibilidad { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encontrado> encontrado { get; set; }
        public virtual estado estado { get; set; }
        public virtual estado estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mensajeria> mensajeria { get; set; }
        public virtual subCategoria subCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicacionFoto> publicacionFoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
